# enable linux 14.04 environment
sudo: required
dist: trusty
language: python

python:
  - "3.3"
  - "3.5"

before_install:
  - sudo locale-gen "en_US.UTF-8"
  - sudo locale-gen "es_ES.UTF-8"
  - sudo update-locale
  - sudo dpkg-reconfigure locales
  - locale | cat -
  - bash .infrastructure/install_icu.sh

install:
  - pip install --upgrade pip
  - pip install pytest
  - pip install pytz
  - pip install --editable .

script:
  - make test
