# enable linux 14.04 environment
sudo: required
dist: trusty

language: python

python:
  - "3.3"
  - "3.5"

install:
  - pip install --upgrade pip
  - pip install pytest
  - pip install pytz
  - pip install --editable .

script:
  - make test
